FROM python:3.12-slim

WORKDIR /work

COPY apps/demo-target/requirements.txt ./demo-requirements.txt
RUN pip install --no-cache-dir -r demo-requirements.txt

COPY frameworks/api-python/requirements.txt ./api-requirements.txt
RUN pip install --no-cache-dir -r api-requirements.txt

COPY apps/demo-target/app ./app
COPY frameworks/api-python .

CMD ["python", "-m", "pytest"]
