"""Unified Visual Report: one HTML dashboard for the whole regression.

Inputs (all optional, missing ones render as 'not run'):
  --junit <glob-or-file>...   JUnit XMLs (playwright, api, newman, karate surefire)
  --coverage coverage.xml     Cobertura XML for the coverage line
  --llm-eval eval-report.json LLM-eval harness JSON
  --title ...                 Report title
  -o ...                      Output HTML path (default reports/visual-report.html)

Stdlib only so it runs in every CI job without extra installs.
"""

import argparse
import glob
import html
import json
import xml.etree.ElementTree as ET
from pathlib import Path


def parse_junit(path: Path):
    try:
        root = ET.parse(path).getroot()
    except Exception as e:
        return {"file": path.name, "error": str(e)}
    suites = root.findall("testsuite") or ([root] if root.tag == "testsuite" else [])
    tests = failures = errors = skipped = 0
    time_s = 0.0
    for s in suites:
        tests += int(s.attrib.get("tests", 0))
        failures += int(s.attrib.get("failures", 0))
        errors += int(s.attrib.get("errors", 0))
        skipped += int(s.attrib.get("skipped", s.attrib.get("skip", 0)))
        time_s += float(s.attrib.get("time", 0))
    return {
        "file": path.name, "tests": tests, "failures": failures,
        "errors": errors, "skipped": skipped, "time_s": round(time_s, 1),
        "passed": tests - failures - errors - skipped,
    }


def parse_coverage(path: Path):
    try:
        root = ET.parse(path).getroot()
        return float(root.attrib.get("line-rate", 0.0))
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--junit", nargs="*", default=[])
    ap.add_argument("--coverage", default="coverage.xml")
    ap.add_argument("--llm-eval", default="evals/llm/eval-report.json")
    ap.add_argument("--title", default="QARonin Visual Report")
    ap.add_argument("-o", "--output", default="reports/visual-report.html")
    args = ap.parse_args()

    junit_files = []
    for pattern in args.junit:
        junit_files.extend(glob.glob(pattern, recursive=True))
    suites = [parse_junit(Path(p)) for p in sorted(set(junit_files))]

    total = sum(s.get("tests", 0) for s in suites if "error" not in s)
    passed = sum(s.get("passed", 0) for s in suites if "error" not in s)
    failed = sum(s.get("failures", 0) + s.get("errors", 0) for s in suites if "error" not in s)
    cov = parse_coverage(Path(args.coverage))

    llm = None
    try:
        llm = json.loads(Path(args.llm_eval).read_text())
    except Exception:
        llm = None

    rows = "\n".join(
        f"<tr><td>{html.escape(s.get('file','?'))}</td><td>{s.get('tests','-')}</td>"
        f"<td>{s.get('passed','-')}</td><td>{s.get('failures',0)+s.get('errors',0) if 'error' not in s else html.escape(s.get('error','?'))}</td>"
        f"<td>{s.get('time_s','-')}</td></tr>"
        for s in suites
    ) or "<tr><td colspan=5>No JUnit files found (pass --junit globs)</td></tr>"

    cov_line = f"{cov*100:.1f}%" if cov is not None else "not run"
    llm_line = f"{llm['passed']}/{llm['total']} (acc={llm['accuracy']})" if llm else "not run"
    verdict = "PASS" if failed == 0 and total > 0 else ("NO DATA" if total == 0 else "FAIL")
    color = {"PASS": "#16a34a", "FAIL": "#dc2626", "NO DATA": "#a16207"}[verdict]

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{html.escape(args.title)}</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem}}
.cards{{display:flex;gap:1rem;flex-wrap:wrap}}.card{{border:1px solid #ddd;border-radius:8px;padding:1rem;flex:1;min-width:160px}}
.verdict{{background:{color};color:#fff;font-weight:700;padding:.25rem .75rem;border-radius:999px}}
table{{border-collapse:collapse;width:100%;margin-top:1rem}}td,th{{border:1px solid #ddd;padding:.4rem .6rem;text-align:left}}
</style></head><body>
<h1>{html.escape(args.title)} <span class="verdict">{verdict}</span></h1>
<div class="cards">
<div class="card"><h3>Total tests</h3><p>{total} ({passed} passed, {failed} failed)</p></div>
<div class="card"><h3>Coverage</h3><p>{cov_line}</p></div>
<div class="card"><h3>LLM-eval</h3><p>{llm_line}</p></div>
</div>
<table><tr><th>Suite</th><th>Tests</th><th>Passed</th><th>Failed</th><th>Time (s)</th></tr>{rows}</table>
<p><small>Generated by tools/visual-report/generate.py. Attach tier budget output and coverage.xml as release records (QMS).</small></p>
</body></html>""")
    print(f"visual report: {total} tests, {failed} failed, coverage={cov_line}, llm={llm_line} -> {out} [{verdict}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
